language:php
php
 -"7.3.5"
 #command to install dependencies
 install:
  -.bin/ci/install_dependencies.sh
  -php vendor/vendors.php
 #command to run tests
 script:
  -phpunit --configuration $DB.phpunit.xml
